version: '3'

services:
  postgres:
    image: 'postgres:latest'
    container_name: 'devices-management-db'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'devices_management'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'devices-api'
    ports:
      - '3000:3000'
    environment:
      DB_HOST: 'postgres'
      DB_PORT: 5432
      DB_USERNAME: 'postgres'
      DB_PASSWORD: 'postgres'
      DB_NAME: 'devices_management'
    depends_on:
      - postgres

volumes:
  postgres_data:      